[package]
name = "bungee_rust"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = { version = "1.32.0", features = ["full"] }
byteorder = "1.4.3"
serde = { version = "1.0.188", features = ["derive"] }
serde_json = "1.0.105"
anyhow = "1.0.75"
async-trait = "0.1.73"
once_cell = "1.18.0"
lazy_static = "1.4.0"

[dependencies.uuid]
version = "1.4.1"
features = ["v3", "v4", "v5"]